apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  db_user: cG9zdGdyZXMuYmZvbWNtbXZkb3d6Z25uamNuZmI=
  db_password: N3g3QmFBU0F2elZwN3YwZw==
  db_host: YXdzLTAtc2EtZWFzdC0xLnBvb2xlci5zdXBhYmFzZS5jb20=
  db_port: NjU0Mw==
  db_name: cG9zdGdyZXM=
