name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      # Recuperar o código
      - name: Checkout
        uses: actions/checkout@v4
