# CI Workflow for building and pushing a Docker image
#
# This workflow is triggered on push events to the `main` branch.
# It builds a Docker image using the `docker build` command and pushes it to a registry.
#
# Example:
# This workflow can be used to automate the build and deployment of a Go application.
# For example, if you have a Go application in the `main` branch of your repository,
# this workflow will build a Docker image with the latest code changes and push it to a registry.

name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      # Recuperar o código
      # Checkout the code in the repository
    - name: Checkout
      uses: actions/checkout@v4

      #gerar tag de acordo com commit
    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=${GITHUB_SHA:0:7}
        echo "sha=$SHA" >> $GITHUB_OUTPUT

      #logar n ocontainer registry
    - name: Login into the cointainer registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          carllos166/nlw-devops-go:${{ steps.generate_sha.outputs.sha }}, 
          carllos166/nlw-devops-go:latest